version: '3'
services:
  studio-dashboard:
    build: 
      context: ./dashboard
    ports:
      - 3000:80
  event-source:
    build: 
      context: ./event_source
    container_name: event-source
    links:
      - mqtt
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./event_source:/usr/src/app

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./EFM_passwords.conf:/mosquitto/config/EFM_passwords.conf
